export interface AIModel {
  name: string;
  provider: string;
  contextWindow: string; // e.g. "200K tokens"
  pricingInput: string; // per 1M tokens
  pricingOutput: string; // per 1M tokens
  maxOutput: string;
  modalities: string[]; // text, image, audio, video
  knowledgeCutoff: string;
  benchMMLU: string; // Massive Multitask Language Understanding
  benchHumanEval: string; // code generation benchmark
  strengths: string[];
  bestUseCases: string[];
}

export const aiModels: AIModel[] = [
  {
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    contextWindow: "200K tokens",
    pricingInput: "$15.00",
    pricingOutput: "$75.00",
    maxOutput: "32K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jan 2026",
    benchMMLU: "89.2%",
    benchHumanEval: "92.1%",
    strengths: ["Complex reasoning", "Code generation", "Long-form analysis", "Instruction following"],
    bestUseCases: ["Agentic coding with large codebases", "Complex multi-step reasoning", "Long document analysis", "Research and academic writing"],
  },
  {
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    contextWindow: "200K tokens",
    pricingInput: "$3.00",
    pricingOutput: "$15.00",
    maxOutput: "16K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jan 2026",
    benchMMLU: "87.5%",
    benchHumanEval: "90.7%",
    strengths: ["Speed/reasoning balance", "Strong coding", "Cost-effective", "Great for daily use"],
    bestUseCases: ["Everyday coding tasks", "Code review and refactoring", "Technical documentation", "General agent workflows"],
  },
  {
    name: "Claude Haiku 4",
    provider: "Anthropic",
    contextWindow: "200K tokens",
    pricingInput: "$0.80",
    pricingOutput: "$4.00",
    maxOutput: "8K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jan 2026",
    benchMMLU: "82.3%",
    benchHumanEval: "85.4%",
    strengths: ["Fastest Claude", "Cheapest", "Good for simple tasks", "Low latency"],
    bestUseCases: ["Simple code completions", "Chat and Q&A", "Data extraction", "High-volume processing"],
  },
  {
    name: "GPT-4.1",
    provider: "OpenAI",
    contextWindow: "1M tokens",
    pricingInput: "$2.00",
    pricingOutput: "$8.00",
    maxOutput: "32K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jun 2025",
    benchMMLU: "88.7%",
    benchHumanEval: "91.5%",
    strengths: ["Massive context (1M)", "Strong instruction following", "Reliable coding", "Code execution"],
    bestUseCases: ["Mega-repository analysis", "Long document processing", "API integration coding", "Enterprise workflows"],
  },
  {
    name: "GPT-4o",
    provider: "OpenAI",
    contextWindow: "128K tokens",
    pricingInput: "$2.50",
    pricingOutput: "$10.00",
    maxOutput: "16K tokens",
    modalities: ["text", "image", "audio"],
    knowledgeCutoff: "Jun 2025",
    benchMMLU: "88.0%",
    benchHumanEval: "90.2%",
    strengths: ["Multi-modal (text+image+audio)", "Fast response", "Vision capabilities", "Balanced performance"],
    bestUseCases: ["Multi-modal analysis", "Screenshot-to-code", "Voice-enabled agents", "Visual QA"],
  },
  {
    name: "GPT-4o Mini",
    provider: "OpenAI",
    contextWindow: "128K tokens",
    pricingInput: "$0.15",
    pricingOutput: "$0.60",
    maxOutput: "16K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jun 2025",
    benchMMLU: "82.0%",
    benchHumanEval: "87.2%",
    strengths: ["Very cheap", "Fast", "Multi-modal", "Good for simple tasks"],
    bestUseCases: ["Cost-sensitive applications", "Simple classification", "Chatbots", "High-throughput processing"],
  },
  {
    name: "o4 Pro",
    provider: "OpenAI",
    contextWindow: "200K tokens",
    pricingInput: "$15.00",
    pricingOutput: "$60.00",
    maxOutput: "100K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Jun 2025",
    benchMMLU: "90.2%",
    benchHumanEval: "94.5%",
    strengths: ["Top-tier reasoning", "Self-fact-checking", "Extensive chain-of-thought", "Math & science"],
    bestUseCases: ["Complex algorithm design", "Mathematical proofs", "Competitive programming", "Research-grade reasoning"],
  },
  {
    name: "o4 Mini",
    provider: "OpenAI",
    contextWindow: "200K tokens",
    pricingInput: "$1.10",
    pricingOutput: "$4.40",
    maxOutput: "100K tokens",
    modalities: ["text"],
    knowledgeCutoff: "Jun 2025",
    benchMMLU: "89.5%",
    benchHumanEval: "93.8%",
    strengths: ["Cost-effective reasoning", "Strong STEM", "Long chain-of-thought", "Free tier available"],
    bestUseCases: ["Budget-constrained complex reasoning", "STEM problem solving", "Code optimization", "Logic puzzles"],
  },
  {
    name: "Gemini 2.5 Pro",
    provider: "Google",
    contextWindow: "1M tokens",
    pricingInput: "$1.25",
    pricingOutput: "$10.00",
    maxOutput: "64K tokens",
    modalities: ["text", "image", "audio", "video"],
    knowledgeCutoff: "Jan 2026",
    benchMMLU: "89.3%",
    benchHumanEval: "91.2%",
    strengths: ["1M context native", "True multi-modal", "Video understanding", "Competitive pricing"],
    bestUseCases: ["Video content analysis", "Massive document processing", "Multi-modal agent systems", "Google Cloud integration"],
  },
  {
    name: "Gemini 2.5 Flash",
    provider: "Google",
    contextWindow: "1M tokens",
    pricingInput: "$0.15",
    pricingOutput: "$0.60",
    maxOutput: "64K tokens",
    modalities: ["text", "image", "audio", "video"],
    knowledgeCutoff: "Jan 2026",
    benchMMLU: "85.5%",
    benchHumanEval: "87.8%",
    strengths: ["Very fast + cheap", "1M context", "Multi-modal", "High throughput"],
    bestUseCases: ["Real-time multi-modal apps", "High-volume classification", "Cost-efficient analysis", "Rapid prototyping"],
  },
  {
    name: "Llama 4 Scout",
    provider: "Meta (via providers)",
    contextWindow: "10M tokens",
    pricingInput: "$0.20",
    pricingOutput: "$0.80",
    maxOutput: "8K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Aug 2025",
    benchMMLU: "86.3%",
    benchHumanEval: "88.5%",
    strengths: ["Massive 10M context", "Open weights", "Cheap", "Multi-provider availability"],
    bestUseCases: ["Ultra-long document analysis", "Repository-wide search", "Open-source agent systems", "Academic research"],
  },
  {
    name: "Llama 4 Maverick",
    provider: "Meta (via providers)",
    contextWindow: "10M tokens",
    pricingInput: "$0.80",
    pricingOutput: "$3.20",
    maxOutput: "32K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Aug 2025",
    benchMMLU: "88.7%",
    benchHumanEval: "90.8%",
    strengths: ["Open weights flagship", "10M context", "Strong reasoning", "Competitive with closed models"],
    bestUseCases: ["Self-hosted agent systems", "Privacy-sensitive applications", "Custom fine-tuned agents", "On-premise deployment"],
  },
  {
    name: "DeepSeek V3",
    provider: "DeepSeek / Providers",
    contextWindow: "128K tokens",
    pricingInput: "$0.27",
    pricingOutput: "$1.10",
    maxOutput: "16K tokens",
    modalities: ["text"],
    knowledgeCutoff: "Jul 2025",
    benchMMLU: "88.5%",
    benchHumanEval: "89.7%",
    strengths: ["Very cheap", "Strong performance", "Open weights", "Multi-provider"],
    bestUseCases: ["Cost-sensitive agent deployments", "High-volume API usage", "Open-source projects", "Budget development"],
  },
  {
    name: "DeepSeek R1",
    provider: "DeepSeek / Providers",
    contextWindow: "128K tokens",
    pricingInput: "$0.55",
    pricingOutput: "$2.19",
    maxOutput: "32K tokens",
    modalities: ["text"],
    knowledgeCutoff: "Jul 2025",
    benchMMLU: "90.8%",
    benchHumanEval: "95.2%",
    strengths: ["Competitive reasoning", "Top-tier coding", "Chain-of-thought", "Open weights reasoning"],
    bestUseCases: ["Algorithmic problem solving", "Complex debugging", "Math and science", "Research-grade coding"],
  },
  {
    name: "Mistral Large 2",
    provider: "Mistral AI",
    contextWindow: "128K tokens",
    pricingInput: "$2.00",
    pricingOutput: "$6.00",
    maxOutput: "16K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Dec 2025",
    benchMMLU: "87.2%",
    benchHumanEval: "89.1%",
    strengths: ["Strong multilingual", "European AI leader", "Good code generation", "Function calling"],
    bestUseCases: ["Multilingual applications", "European compliance needs", "Function-calling agents", "Balanced general use"],
  },
  {
    name: "Qwen 3",
    provider: "Alibaba / Providers",
    contextWindow: "128K tokens",
    pricingInput: "$0.30",
    pricingOutput: "$1.00",
    maxOutput: "16K tokens",
    modalities: ["text", "image", "audio", "video"],
    knowledgeCutoff: "Mar 2026",
    benchMMLU: "87.8%",
    benchHumanEval: "88.9%",
    strengths: ["Full multi-modal", "Open source", "Cheap", "Chinese/English bilingual"],
    bestUseCases: ["Asian language applications", "Multi-modal agent systems", "Cost-effective deployment", "Open-source customization"],
  },
  {
    name: "Grok 4",
    provider: "xAI / Providers",
    contextWindow: "1M tokens",
    pricingInput: "$2.00",
    pricingOutput: "$8.00",
    maxOutput: "32K tokens",
    modalities: ["text", "image"],
    knowledgeCutoff: "Apr 2026",
    benchMMLU: "88.5%",
    benchHumanEval: "90.1%",
    strengths: ["Real-time knowledge", "Strong reasoning", "Large context", "Unfiltered style"],
    bestUseCases: ["Real-time news analysis", "Unfiltered technical discussion", "Large-scale data analysis", "X/Twitter integration"],
  },
  {
    name: "Command R+",
    provider: "Cohere",
    contextWindow: "128K tokens",
    pricingInput: "$3.00",
    pricingOutput: "$15.00",
    maxOutput: "4K tokens",
    modalities: ["text"],
    knowledgeCutoff: "Sep 2025",
    benchMMLU: "85.3%",
    benchHumanEval: "85.8%",
    strengths: ["Enterprise RAG", "Tool use specialist", "Multi-step tool calling", "Citation accuracy"],
    bestUseCases: ["Enterprise RAG pipelines", "Tool-use agent systems", "Document QA with citations", "Enterprise search applications"],
  },
];

export const modelProviders = [
  "Anthropic",
  "OpenAI",
  "Google",
  "Meta",
  "DeepSeek / Providers",
  "Mistral AI",
  "Alibaba / Providers",
  "xAI / Providers",
  "Cohere",
];
