export interface Skill {
  name: string;
  description: string;
  triggers: string[];
  category: "process" | "design" | "media-gen" | "tooling" | "code" | "docs";
  combos: string[];
  whenToUse: string;
}

export const skills: Skill[] = [
  {
    name: "brainstorming",
    description: "Explores user intent, requirements and design before any creative work — creating features, building components, adding functionality, or modifying behavior.",
    triggers: ["brainstorm", "design discussion", "feature planning", "creative work"],
    category: "process",
    combos: ["writing-plans", "frontend-design", "grill-me"],
    whenToUse: "Before any creative or implementation work. Use to refine ideas into designs through structured dialogue.",
  },
  {
    name: "writing-plans",
    description: "Creates detailed implementation plans when you have a spec or requirements for a multi-step task, before touching code.",
    triggers: ["write a plan", "implementation plan", "create plan", "plan this out"],
    category: "process",
    combos: ["brainstorming", "executing-plans", "subagent-driven-development"],
    whenToUse: "After design is approved. Converts spec into actionable implementation steps.",
  },
  {
    name: "executing-plans",
    description: "Executes a written implementation plan in a separate session with review checkpoints.",
    triggers: ["execute plan", "run the plan", "implement the plan"],
    category: "process",
    combos: ["writing-plans", "using-git-worktrees", "finishing-a-development-branch"],
    whenToUse: "When you want parallel session execution with human-in-loop checkpoints.",
  },
  {
    name: "subagent-driven-development",
    description: "Executes plans by dispatching fresh subagent per task with two-stage review: spec compliance then code quality.",
    triggers: ["subagent", "dispatch tasks", "parallel implementation"],
    category: "process",
    combos: ["writing-plans", "tdd", "finishing-a-development-branch"],
    whenToUse: "For same-session execution of independent tasks with automatic review gates.",
  },
  {
    name: "dispatching-parallel-agents",
    description: "Use when facing 2+ independent tasks that can be worked on without shared state or sequential dependencies.",
    triggers: ["parallel tasks", "independent work", "dispatch agents"],
    category: "process",
    combos: ["writing-plans", "subagent-driven-development"],
    whenToUse: "When tasks have no shared state and can run concurrently.",
  },
  {
    name: "finishing-a-development-branch",
    description: "Guides completion of development work by presenting structured options for merge, PR, or cleanup when implementation is complete and tests pass.",
    triggers: ["finish branch", "wrap up", "complete development", "ready to merge"],
    category: "process",
    combos: ["executing-plans", "subagent-driven-development", "requesting-code-review"],
    whenToUse: "After all implementation tasks are done. Helps decide merge/PR/cleanup strategy.",
  },
  {
    name: "using-git-worktrees",
    description: "Ensures an isolated workspace exists via native tools or git worktree fallback when starting feature work.",
    triggers: ["git worktree", "isolated workspace", "separate branch work"],
    category: "process",
    combos: ["executing-plans", "writing-plans"],
    whenToUse: "Before starting feature work that needs isolation from current workspace.",
  },
  {
    name: "diagnose",
    description: "Disciplined diagnosis loop for hard bugs and performance regressions. Reproduce → minimise → hypothesise → instrument → fix → regression-test.",
    triggers: ["diagnose this", "debug this", "broken", "bug", "performance regression"],
    category: "process",
    combos: ["systematic-debugging", "verification-before-completion"],
    whenToUse: "For hard bugs and perf issues. Follow the scientific method: reproduce, minimize, fix.",
  },
  {
    name: "systematic-debugging",
    description: "Systematic approach to debugging — use when encountering any bug, test failure, or unexpected behavior, before proposing fixes.",
    triggers: ["bug", "test failure", "unexpected behavior", "something wrong"],
    category: "process",
    combos: ["diagnose", "tdd", "verification-before-completion"],
    whenToUse: "First response to any bug. Understand before fixing.",
  },
  {
    name: "tdd",
    description: "Test-driven development with red-green-refactor loop for building features or fixing bugs.",
    triggers: ["TDD", "red-green-refactor", "test first", "integration tests"],
    category: "process",
    combos: ["systematic-debugging", "writing-plans", "subagent-driven-development"],
    whenToUse: "When building features or fixing bugs with test-first discipline.",
  },
  {
    name: "test-driven-development",
    description: "Use when implementing any feature or bugfix, before writing implementation code.",
    triggers: ["implement feature", "fix bug", "write code"],
    category: "process",
    combos: ["systematic-debugging", "writing-plans"],
    whenToUse: "Before writing any implementation code. Write tests first.",
  },
  {
    name: "verification-before-completion",
    description: "Requires running verification commands and confirming output before making any success claims. Evidence before assertions always.",
    triggers: ["complete", "fixed", "passing", "done"],
    category: "process",
    combos: ["tdd", "diagnose", "systematic-debugging"],
    whenToUse: "Before claiming work is done. Run verification, show evidence.",
  },
  {
    name: "requesting-code-review",
    description: "Use when completing tasks, implementing major features, or before merging to verify work meets requirements.",
    triggers: ["code review", "review my code", "check my work"],
    category: "process",
    combos: ["finishing-a-development-branch", "receiving-code-review"],
    whenToUse: "After completing significant work, before merging.",
  },
  {
    name: "receiving-code-review",
    description: "Use when receiving code review feedback, before implementing suggestions. Requires technical rigor and verification.",
    triggers: ["review feedback", "PR comments", "code review response"],
    category: "process",
    combos: ["requesting-code-review", "verification-before-completion"],
    whenToUse: "When processing review feedback — verify before implementing.",
  },
  {
    name: "improve-codebase-architecture",
    description: "Finds deepening opportunities in a codebase, informed by domain language in CONTEXT.md and decisions in docs/adr/.",
    triggers: ["improve architecture", "refactor", "consolidate modules", "codebase health"],
    category: "process",
    combos: ["zoom-out", "brainstorming", "setup-matt-pocock-skills"],
    whenToUse: "For architectural improvements, refactoring, making codebase more testable.",
  },
  {
    name: "zoom-out",
    description: "Provides broader context or higher-level perspective on a section of code and how it fits into the bigger picture.",
    triggers: ["zoom out", "bigger picture", "how does this fit", "context"],
    category: "process",
    combos: ["improve-codebase-architecture", "brainstorming"],
    whenToUse: "When unfamiliar with code and need to understand its role in the system.",
  },
  {
    name: "setup-matt-pocock-skills",
    description: "Sets up agent skills block in AGENTS.md/CLAUDE.md and docs/agents/ with issue tracker, triage labels, and domain doc layout.",
    triggers: ["setup skills", "configure agents", "project setup"],
    category: "process",
    combos: ["improve-codebase-architecture", "to-issues", "to-prd", "triage"],
    whenToUse: "Run before first use of engineering skills (to-issues, to-prd, triage, diagnose, tdd).",
  },
  {
    name: "to-issues",
    description: "Breaks a plan, spec, or PRD into independently-grabbable issues using tracer-bullet vertical slices.",
    triggers: ["create issues", "break down work", "implementation tickets"],
    category: "process",
    combos: ["writing-plans", "to-prd", "setup-matt-pocock-skills"],
    whenToUse: "When converting a plan/spec into actionable issue tracker tickets.",
  },
  {
    name: "to-prd",
    description: "Turns the current conversation context into a PRD and publishes it to the project issue tracker.",
    triggers: ["create PRD", "write PRD", "product requirements"],
    category: "process",
    combos: ["brainstorming", "to-issues", "setup-matt-pocock-skills"],
    whenToUse: "When you need to formalize conversation context into a product requirements document.",
  },
  {
    name: "triage",
    description: "Triages issues through a state machine driven by triage roles — create, review, prepare for AFK agent, manage workflow.",
    triggers: ["triage", "review issues", "incoming bugs", "issue workflow"],
    category: "process",
    combos: ["to-issues", "setup-matt-pocock-skills", "diagnose"],
    whenToUse: "For managing issue workflow: triage incoming bugs and feature requests.",
  },
  {
    name: "grill-me",
    description: "Interviews the user relentlessly about a plan or design until reaching shared understanding, resolving each branch of the decision tree.",
    triggers: ["grill me", "stress-test my plan", "challenge my design"],
    category: "process",
    combos: ["brainstorming", "grill-with-docs"],
    whenToUse: "When you want your plan/design stress-tested with hard questions.",
  },
  {
    name: "grill-with-docs",
    description: "Grilling session that challenges your plan against existing domain model, sharpens terminology, and updates documentation inline.",
    triggers: ["grill with docs", "stress-test against docs", "challenge with context"],
    category: "process",
    combos: ["grill-me", "brainstorming", "improve-codebase-architecture"],
    whenToUse: "When stress-testing a plan against existing project documentation and decisions.",
  },
  {
    name: "handoff",
    description: "Compacts the current conversation into a handoff document for another agent to pick up.",
    triggers: ["handoff", "pass to another agent", "context transfer"],
    category: "process",
    combos: ["writing-plans", "executing-plans"],
    whenToUse: "When transferring work context between agents or sessions.",
  },
  {
    name: "prototype",
    description: "Builds a throwaway prototype to flesh out a design — terminal app for logic questions or UI variations toggleable from one route.",
    triggers: ["prototype", "mockup", "try a few designs", "let me play with it"],
    category: "process",
    combos: ["brainstorming", "frontend-design"],
    whenToUse: "Before committing to a design — quickly validate ideas with runnable prototypes.",
  },
  {
    name: "teach",
    description: "Teaches the user a new skill or concept within the current workspace.",
    triggers: ["teach me", "learn", "explain concept", "how does X work"],
    category: "process",
    combos: ["brainstorming"],
    whenToUse: "When the user wants to learn a new skill or understand a concept.",
  },
  {
    name: "using-superpowers",
    description: "Establishes how to find and use skills, requiring Skill tool invocation before ANY response including clarifying questions.",
    triggers: ["start conversation", "begin", "how to use skills"],
    category: "process",
    combos: ["find-skills", "skill-creator"],
    whenToUse: "Auto-loaded at start. Teaches how to discover and invoke skills.",
  },
  {
    name: "find-skills",
    description: "Helps users discover and install agent skills when they ask how to do something or want to extend capabilities.",
    triggers: ["find a skill", "how do I do X", "is there a skill for", "install skill"],
    category: "process",
    combos: ["using-superpowers", "skill-creator"],
    whenToUse: "When looking for functionality that might exist as an installable skill.",
  },
  {
    name: "skill-creator",
    description: "Creates new skills, modifies and improves existing skills, measures skill performance, runs evals, and benchmarks.",
    triggers: ["create skill", "write skill", "edit skill", "optimize skill", "skill evals"],
    category: "process",
    combos: ["write-a-skill", "writing-skills", "find-skills"],
    whenToUse: "For creating, editing, optimizing, or benchmarking agent skills.",
  },
  {
    name: "write-a-skill",
    description: "Creates new agent skills with proper structure, progressive disclosure, and bundled resources.",
    triggers: ["write a skill", "create a new skill", "build a skill"],
    category: "process",
    combos: ["skill-creator", "writing-skills"],
    whenToUse: "When creating a brand new skill from scratch.",
  },
  {
    name: "writing-skills",
    description: "Use when creating new skills, editing existing skills, or verifying skills work before deployment.",
    triggers: ["write skill", "edit skill", "verify skill"],
    category: "process",
    combos: ["skill-creator", "write-a-skill"],
    whenToUse: "For the full skill lifecycle: create, edit, verify before deployment.",
  },
  {
    name: "template-skill",
    description: "Template for creating new skills. Replace with description of the skill and when Claude should use it.",
    triggers: [],
    category: "process",
    combos: ["skill-creator"],
    whenToUse: "Starting point for creating a new skill.",
  },
  {
    name: "doc-coauthoring",
    description: "Structured workflow for co-authoring documentation — proposals, technical specs, decision docs. Helps transfer context and refine through iteration.",
    triggers: ["write docs", "proposal", "technical spec", "decision doc"],
    category: "docs",
    combos: ["brainstorming", "writing-guidelines"],
    whenToUse: "When writing documentation, proposals, or structured technical content.",
  },
  {
    name: "writing-guidelines",
    description: "Reviews docs/prose for Writing Guidelines compliance — voice, tone, clarity, and consistency.",
    triggers: ["review my docs", "check writing style", "audit prose", "writing handbook"],
    category: "docs",
    combos: ["doc-coauthoring", "internal-comms"],
    whenToUse: "After writing docs — audit for voice, tone, and style compliance.",
  },
  {
    name: "internal-comms",
    description: "Resources for writing internal communications using company formats — status reports, leadership updates, newsletters, FAQs, incident reports.",
    triggers: ["status report", "leadership update", "newsletter", "FAQ", "incident report", "project update"],
    category: "docs",
    combos: ["writing-guidelines", "docx"],
    whenToUse: "For any internal communication: status reports, updates, newsletters, incident reports.",
  },
  {
    name: "docx",
    description: "Create, read, edit, or manipulate Word documents (.docx) — reports, memos, letters, templates with professional formatting.",
    triggers: ["Word doc", "word document", ".docx", "report", "memo", "letter", "template"],
    category: "docs",
    combos: ["pdf", "writing-guidelines", "internal-comms"],
    whenToUse: "Any time a .docx file is involved — creating, editing, or extracting content.",
  },
  {
    name: "pdf",
    description: "Everything PDF — reading, extracting text/tables, merging, splitting, rotating, watermarking, creating, form filling, encrypting, OCR.",
    triggers: [".pdf", "PDF file", "extract from PDF", "merge PDFs", "OCR"],
    category: "docs",
    combos: ["docx", "xlsx", "pptx"],
    whenToUse: "Any PDF operation: read, create, merge, split, extract, OCR, forms.",
  },
  {
    name: "pptx",
    description: "Create, read, edit PowerPoint presentations (.pptx) — slide decks, pitch decks, templates, layouts, speaker notes.",
    triggers: ["deck", "slides", "presentation", ".pptx", "pitch deck"],
    category: "docs",
    combos: ["theme-factory", "brand-guidelines", "pdf"],
    whenToUse: "Any .pptx task: creating decks, reading slides, editing presentations.",
  },
  {
    name: "xlsx",
    description: "Open, read, edit, create spreadsheets — .xlsx, .xlsm, .csv, .tsv. Formulas, formatting, charts, data cleaning, conversions.",
    triggers: [".xlsx", "spreadsheet", ".csv", "Excel", "tabular data"],
    category: "docs",
    combos: ["pdf", "docx"],
    whenToUse: "When spreadsheet is primary input/output — editing, creating, cleaning data.",
  },
  {
    name: "theme-factory",
    description: "Toolkit for styling artifacts with a theme — slides, docs, reports, HTML pages. 10 pre-set themes or generate new ones on-the-fly.",
    triggers: ["theme", "style this", "apply theme", "color scheme"],
    category: "design",
    combos: ["pptx", "canvas-design", "brand-guidelines"],
    whenToUse: "When any artifact needs themed styling with colors and fonts.",
  },
  {
    name: "brand-guidelines",
    description: "Applies Anthropic's official brand colors and typography to any artifact needing the company look-and-feel.",
    triggers: ["brand colors", "style guidelines", "visual formatting", "company design"],
    category: "design",
    combos: ["theme-factory", "pptx", "canvas-design"],
    whenToUse: "When brand colors, style guidelines, or company design standards apply.",
  },
  {
    name: "frontend-design",
    description: "Guidance for distinctive, intentional visual design when building new UI or reshaping existing one — aesthetic direction, typography, anti-template choices.",
    triggers: ["design UI", "visual design", "aesthetic", "typography"],
    category: "design",
    combos: ["brainstorming", "design-taste-frontend", "minimalist-ui"],
    whenToUse: "When building new UI or redesigning — helps avoid templated defaults.",
  },
  {
    name: "design-taste-frontend",
    description: "Anti-slop frontend skill for landing pages, portfolios, and redesigns. Reads the brief, infers design direction, ships interfaces that don't look templated.",
    triggers: ["landing page", "portfolio", "redesign", "frontend design"],
    category: "design",
    combos: ["frontend-design", "imagegen-frontend-web", "redesign-existing-projects"],
    whenToUse: "For landing pages, portfolios, and redesigns that need distinctive visual identity.",
  },
  {
    name: "design-taste-frontend-v1",
    description: "Original v1 taste-skill preserved for projects depending on its exact behavior. Current default is design-taste-frontend (v2).",
    triggers: ["v1 design", "original taste skill", "backward compat design"],
    category: "design",
    combos: ["frontend-design"],
    whenToUse: "Only if you need exact backward compatibility with v1 behavior.",
  },
  {
    name: "high-end-visual-design",
    description: "Teaches the AI to design like a high-end agency. Exact fonts, spacing, shadows, card structures, and animations that make a website feel expensive.",
    triggers: ["premium design", "expensive look", "agency quality", "high end"],
    category: "design",
    combos: ["frontend-design", "design-taste-frontend", "gpt-taste"],
    whenToUse: "When building premium, agency-quality interfaces that block common AI defaults.",
  },
  {
    name: "gpt-taste",
    description: "Elite UX/UI & Advanced GSAP Motion Engineer. Python-driven true randomization, strict AIDA page structure, wide editorial typography, gapless bento grids.",
    triggers: ["GSAP", "scroll animation", "bento grid", "advanced animation"],
    category: "design",
    combos: ["high-end-visual-design", "frontend-design", "design-taste-frontend"],
    whenToUse: "For advanced GSAP ScrollTrigger animations, bento grids, and motion-heavy pages.",
  },
  {
    name: "minimalist-ui",
    description: "Clean editorial-style interfaces. Warm monochrome palette, typographic contrast, flat bento grids, muted pastels. No gradients, no heavy shadows.",
    triggers: ["minimalist", "clean design", "editorial", "simple UI"],
    category: "design",
    combos: ["frontend-design", "industrial-brutalist-ui"],
    whenToUse: "When you want warm, editorial minimalism — monochrome, flat, muted.",
  },
  {
    name: "industrial-brutalist-ui",
    description: "Raw mechanical interfaces fusing Swiss typographic print with military terminal aesthetics. Rigid grids, extreme type scale contrast, utilitarian color.",
    triggers: ["brutalist", "industrial", "terminal", "utilitarian", "raw design"],
    category: "design",
    combos: ["minimalist-ui", "frontend-design"],
    whenToUse: "For data-heavy dashboards, portfolios, or editorial sites needing declassified blueprint feel.",
  },
  {
    name: "imagegen-frontend-web",
    description: "Elite frontend image-direction skill for premium, conversion-aware website design references. ONE separate horizontal image FOR EVERY section.",
    triggers: ["design reference", "website mockup", "landing page image", "section design"],
    category: "design",
    combos: ["design-taste-frontend", "image-to-code", "ai-image-generation"],
    whenToUse: "When generating visual design references for web pages — one image per section.",
  },
  {
    name: "imagegen-frontend-mobile",
    description: "Elite mobile app image-generation for premium, app-native screen concepts — iOS, Android, cross-platform. Clean hierarchy, tasteful iconography, phone mockup framing.",
    triggers: ["mobile design", "app screens", "iOS design", "Android design"],
    category: "design",
    combos: ["design-taste-frontend", "sleek-design-mobile-apps", "ai-image-generation"],
    whenToUse: "For generating mobile app screen concepts and design references.",
  },
  {
    name: "image-to-code",
    description: "Elite website image-to-code skill. Generates design images first, analyzes them, then implements website to match. Prefers large, readable, section-specific images.",
    triggers: ["image to code", "design to code", "screenshot to code", "implement from design"],
    category: "design",
    combos: ["imagegen-frontend-web", "design-taste-frontend", "frontend-design"],
    whenToUse: "When converting visual designs into working code with high fidelity.",
  },
  {
    name: "redesign-existing-projects",
    description: "Upgrades existing websites and apps to premium quality. Audits current design, identifies generic AI patterns, applies high-end standards without breaking functionality.",
    triggers: ["redesign", "upgrade UI", "fix design", "improve existing site"],
    category: "design",
    combos: ["design-taste-frontend", "frontend-design", "web-design-guidelines"],
    whenToUse: "When upgrading an existing project's design quality without rewriting functionality.",
  },
  {
    name: "canvas-design",
    description: "Creates beautiful visual art in .png and .pdf documents using design philosophy — posters, art, static pieces. Original work, never copies existing artists.",
    triggers: ["poster", "art", "design piece", "visual", "create a design"],
    category: "design",
    combos: ["theme-factory", "brand-guidelines", "brandkit"],
    whenToUse: "For creating static visual art, posters, or design pieces as .png or .pdf.",
  },
  {
    name: "algorithmic-art",
    description: "Creates algorithmic art using p5.js with seeded randomness and interactive parameter exploration — generative art, flow fields, particle systems.",
    triggers: ["generative art", "algorithmic art", "flow field", "particle system", "creative coding"],
    category: "design",
    combos: ["canvas-design", "prototype"],
    whenToUse: "For code-based generative art using p5.js with interactive exploration.",
  },
  {
    name: "brandkit",
    description: "Premium brand-kit image generation for high-end brand-guidelines boards, logo systems, identity decks, and visual-world presentations.",
    triggers: ["brand kit", "logo system", "identity deck", "brand guidelines board"],
    category: "design",
    combos: ["canvas-design", "brand-guidelines", "theme-factory"],
    whenToUse: "For creating premium brand identity systems, logos, and visual worlds.",
  },
  {
    name: "slack-gif-creator",
    description: "Knowledge and utilities for creating animated GIFs optimized for Slack — constraints, validation tools, and animation concepts.",
    triggers: ["Slack GIF", "animated GIF", "make me a GIF for Slack"],
    category: "design",
    combos: ["canvas-design", "algorithmic-art"],
    whenToUse: "When creating animated GIFs that meet Slack's constraints and look good.",
  },
  {
    name: "sleek-design-mobile-apps",
    description: "Design mobile apps, create screens, build UI, or interact with Sleek projects — high-level requests and specific ones.",
    triggers: ["design mobile app", "create screens", "Sleek project", "mobile UI"],
    category: "design",
    combos: ["imagegen-frontend-mobile", "frontend-design"],
    whenToUse: "When designing mobile apps or interacting with Sleek projects.",
  },
  {
    name: "stitch-design-taste",
    description: "Semantic Design System Skill for Google Stitch. Generates agent-friendly DESIGN.md files enforcing premium, anti-generic UI standards.",
    triggers: ["Stitch", "DESIGN.md", "design system", "Google Stitch"],
    category: "design",
    combos: ["frontend-design", "high-end-visual-design"],
    whenToUse: "When working with Google Stitch design system or generating DESIGN.md files.",
  },
  {
    name: "shadcn",
    description: "Manages shadcn components and projects — adding, searching, fixing, debugging, styling, and composing UI with component registries and presets.",
    triggers: ["shadcn", "shadcn/ui", "components.json", "shadcn init", "preset"],
    category: "code",
    combos: ["frontend-design", "vercel-composition-patterns", "web-artifacts-builder"],
    whenToUse: "When working with shadcn/ui components, registries, presets, or component libraries.",
  },
  {
    name: "vercel-react-best-practices",
    description: "React and Next.js performance optimization guidelines from Vercel Engineering for components, pages, data fetching, and bundle optimization.",
    triggers: ["React performance", "Next.js optimization", "bundle size", "data fetching pattern"],
    category: "code",
    combos: ["vercel-composition-patterns", "vercel-optimize", "shadcn"],
    whenToUse: "When writing, reviewing, or refactoring React/Next.js code for performance.",
  },
  {
    name: "vercel-composition-patterns",
    description: "React composition patterns that scale — compound components, render props, context providers, component architecture. Includes React 19 API changes.",
    triggers: ["compound components", "render props", "context provider", "component library", "React 19"],
    category: "code",
    combos: ["vercel-react-best-practices", "shadcn"],
    whenToUse: "When building flexible component libraries or refactoring boolean prop proliferation.",
  },
  {
    name: "vercel-react-view-transitions",
    description: "Guide for implementing smooth animations using React's View Transition API — page transitions, route changes, shared element animations, list reorder.",
    triggers: ["view transitions", "page transition", "route animation", "shared element", "startViewTransition"],
    category: "code",
    combos: ["vercel-react-best-practices", "frontend-design", "gpt-taste"],
    whenToUse: "For implementing native-feeling view transitions without third-party animation libraries.",
  },
  {
    name: "vercel-react-native-skills",
    description: "React Native and Expo best practices for building performant mobile apps — components, list performance, animations, native modules.",
    triggers: ["React Native", "Expo", "mobile performance", "native module"],
    category: "code",
    combos: ["sleek-design-mobile-apps", "vercel-react-best-practices"],
    whenToUse: "When building React Native or Expo apps with performance considerations.",
  },
  {
    name: "vercel-optimize",
    description: "Vercel cost and performance optimization for deployed projects — bill reduction, slow routes, caching, Function Invocations, Build Minutes, Core Web Vitals.",
    triggers: ["Vercel cost", "slow route", "caching", "bill reduction", "Core Web Vitals"],
    category: "code",
    combos: ["vercel-react-best-practices", "deploy-to-vercel", "vercel-cli-with-tokens"],
    whenToUse: "For optimizing deployed Next.js/SvelteKit/Nuxt apps on Vercel — cost and performance.",
  },
  {
    name: "web-artifacts-builder",
    description: "Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using React, Tailwind CSS, shadcn/ui — state management, routing.",
    triggers: ["HTML artifact", "web artifact", "complex artifact", "multi-component"],
    category: "code",
    combos: ["shadcn", "frontend-design", "vercel-react-best-practices"],
    whenToUse: "For complex claude.ai artifacts needing state management, routing, or shadcn/ui components.",
  },
  {
    name: "webapp-testing",
    description: "Toolkit for interacting with and testing local web applications using Playwright — verifying frontend functionality, debugging UI, screenshots, browser logs.",
    triggers: ["test web app", "Playwright", "browser test", "UI test", "screenshot"],
    category: "code",
    combos: ["tdd", "systematic-debugging", "verification-before-completion"],
    whenToUse: "For testing local web apps with Playwright: screenshots, logs, UI verification.",
  },
  {
    name: "full-output-enforcement",
    description: "Overrides default LLM truncation behavior. Enforces complete code generation, bans placeholder patterns, and handles token-limit splits cleanly.",
    triggers: ["complete code", "no truncation", "full output", "exhaustive generation"],
    category: "code",
    combos: ["writing-plans", "subagent-driven-development"],
    whenToUse: "For tasks requiring exhaustive, unabridged code output without placeholders.",
  },
  {
    name: "caveman",
    description: "Ultra-compressed communication mode. Cuts token usage ~75% by dropping filler, articles, and pleasantries while keeping full technical accuracy.",
    triggers: ["caveman mode", "talk like caveman", "use caveman", "less tokens", "be brief"],
    category: "process",
    combos: ["full-output-enforcement"],
    whenToUse: "When you want minimal token usage — drops fluff, keeps technical accuracy.",
  },
  {
    name: "ai-image-generation",
    description: "Smart router across full image-model catalog on RunComfy — FLUX 2, Nano Banana 2/Pro, GPT Image 2, Seedream 5/4-5/4-0, Qwen Image, Z-Image Turbo, Wan 2-7.",
    triggers: ["generate image", "make a picture", "text to image", "AI image", "i2i", "image to image"],
    category: "media-gen",
    combos: ["runcomfy-cli", "image-edit", "imagegen-frontend-web"],
    whenToUse: "For any image generation or image-to-image task — picks the right model automatically.",
  },
  {
    name: "image-edit",
    description: "Smart router for image editing — Nano Banana Edit, GPT Image 2 Edit, Flux Kontext Pro, Z-Image Turbo Inpaint. Swaps backgrounds, removes objects, rewrites text.",
    triggers: ["image edit", "edit image", "swap background", "remove object", "rewrite headline"],
    category: "media-gen",
    combos: ["ai-image-generation", "runcomfy-cli", "image-inpainting"],
    whenToUse: "For any image editing task — routes to best model based on intent.",
  },
  {
    name: "image-inpainting",
    description: "Mask-driven image inpainting — object removal, watermark removal, region replacement, blemish cleanup. Routes to Z-Image Turbo Inpainting and identity-preserving edit models.",
    triggers: ["inpaint", "inpainting", "remove from image", "fill region", "remove watermark", "remove object"],
    category: "media-gen",
    combos: ["image-edit", "ai-image-generation", "runcomfy-cli"],
    whenToUse: "For mask-driven local edits — remove objects, watermarks, fill regions.",
  },
  {
    name: "image-outpainting",
    description: "Extend still images beyond original canvas — change aspect ratio, uncrop, fill surroundings while preserving original content.",
    triggers: ["outpaint", "outpainting", "extend canvas", "uncrop", "change aspect ratio", "expand frame"],
    category: "media-gen",
    combos: ["image-edit", "ai-image-generation", "runcomfy-cli"],
    whenToUse: "For extending images beyond original canvas — uncrop, change aspect ratio.",
  },
  {
    name: "relight",
    description: "Relight a still image — change lighting setup, color temperature, direction, or mood. Product relighting, portrait mood shift, color-grade change.",
    triggers: ["relight", "relighting", "change lighting", "golden hour", "studio lighting", "rim light"],
    category: "media-gen",
    combos: ["image-edit", "ai-image-generation", "runcomfy-cli"],
    whenToUse: "For changing lighting on still images — product relight, mood shift, color grade.",
  },
  {
    name: "flux-2-klein",
    description: "Generate images with Flux 2 Klein (Black Forest Labs' distilled fast variant) — sub-second latency, multi-reference brand styling, declarative prompts.",
    triggers: ["flux 2 klein", "flux klein", "BFL flux 2", "fast image gen"],
    category: "media-gen",
    combos: ["ai-image-generation", "runcomfy-cli", "flux-kontext"],
    whenToUse: "When you specifically want Flux 2 Klein's fast, distilled image generation.",
  },
  {
    name: "flux-kontext",
    description: "Edit images with Flux 1 Kontext Pro — single-reference precise local edits, strong prompt control, consistent high-fidelity outputs.",
    triggers: ["flux kontext", "flux 1 kontext", "kontext", "BFL kontext"],
    category: "media-gen",
    combos: ["image-edit", "flux-2-klein", "runcomfy-cli"],
    whenToUse: "For precise local edits with strong identity preservation using Flux Kontext.",
  },
  {
    name: "gpt-image-2",
    description: "Generate and edit images with OpenAI GPT Image 2 — embedded text, logos, multilingual typography, instruction precision. 3 fixed sizes.",
    triggers: ["gpt image 2", "ChatGPT Images 2", "image 2", "GPT image gen"],
    category: "media-gen",
    combos: ["ai-image-generation", "gpt-image-edit", "runcomfy-cli"],
    whenToUse: "When you need embedded text, logos, or multilingual typography in images.",
  },
  {
    name: "gpt-image-edit",
    description: "Edit images with GPT Image 2 edit endpoint — preservation language, in-image text editing, multi-reference up to 10 images, layout precision.",
    triggers: ["gpt image edit", "edit with gpt image 2", "chatgpt image edit"],
    category: "media-gen",
    combos: ["gpt-image-2", "image-edit", "runcomfy-cli"],
    whenToUse: "For precise multi-reference image edits with text/layout preservation.",
  },
  {
    name: "nano-banana-2",
    description: "Generate images with Google Nano Banana 2 (Gemini flash-tier) — rapid iteration, in-image typography, predictable framing, optional web-grounded context.",
    triggers: ["nano banana", "google image gen", "gemini image", "nano banana 2"],
    category: "media-gen",
    combos: ["ai-image-generation", "nano-banana-edit", "runcomfy-cli"],
    whenToUse: "For rapid iteration image generation with Google's flash-tier model.",
  },
  {
    name: "nano-banana-edit",
    description: "Edit images with Google Nano Banana 2 edit endpoint — preserve subject identity, swap background, spatial language edits, batch up to 20 images.",
    triggers: ["nano banana edit", "edit with nano banana", "image edit nano banana"],
    category: "media-gen",
    combos: ["nano-banana-2", "image-edit", "runcomfy-cli"],
    whenToUse: "For batch image edits (up to 20) with identity preservation and background swaps.",
  },
  {
    name: "ai-video-generation",
    description: "Smart router across full video-model catalog — HappyHorse 1.0, Wan 2-7, Seedance v2, Kling 3.0/2-6, Veo 3-1, Hailuo 2-3, Dreamina 3-0. Text-to-video and image-to-video.",
    triggers: ["generate video", "make a video", "text to video", "t2v", "animate", "AI video", "image to video"],
    category: "media-gen",
    combos: ["runcomfy-cli", "image-to-video", "video-edit"],
    whenToUse: "For any video generation task — picks the best model based on intent and quality needs.",
  },
  {
    name: "image-to-video",
    description: "Animate any still image — HappyHorse 1.0 I2V, Wan 2.7 with audio_url lip-sync, or Seedance 2.0 Pro multi-modal animation.",
    triggers: ["image to video", "i2v", "animate image", "make this move"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "ai-image-generation"],
    whenToUse: "When turning a still image into a video — animation, lip-sync, or multi-modal.",
  },
  {
    name: "video-edit",
    description: "Edit existing video — Wan 2.7 Edit-Video (restyle/background swap), Kling 2.6 Pro Motion Control (motion transfer), Lucy Edit Restyle (outfit swap).",
    triggers: ["video edit", "edit video", "restyle video", "swap video background", "motion control", "outfit swap video"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "video-extend"],
    whenToUse: "For transforming existing video — restyle, background swap, motion transfer.",
  },
  {
    name: "video-extend",
    description: "Extend or continue existing video clips — Google Veo 3-1 extend-video. Consistent motion, lighting, and subject identity across continuation.",
    triggers: ["extend video", "continue video", "longer video", "make this clip longer", "Veo extend", "chain video shots"],
    category: "media-gen",
    combos: ["ai-video-generation", "video-edit", "runcomfy-cli"],
    whenToUse: "When a video clip needs to be longer with consistent motion and identity.",
  },
  {
    name: "video-inpainting",
    description: "Region edits across video frames — remove objects, clean up wires/watermarks, replace regions with matching motion.",
    triggers: ["video inpaint", "remove from video", "mask region in video", "remove object from clip", "video patch"],
    category: "media-gen",
    combos: ["video-edit", "image-inpainting", "runcomfy-cli"],
    whenToUse: "For removing objects or watermarks across multiple video frames.",
  },
  {
    name: "video-outpainting",
    description: "Extend spatial canvas of video — change aspect ratio (vertical to horizontal), add environment beyond original frame.",
    triggers: ["video outpaint", "extend video canvas", "uncrop video", "aspect ratio change", "TikTok to YouTube"],
    category: "media-gen",
    combos: ["video-edit", "image-outpainting", "runcomfy-cli"],
    whenToUse: "For changing video aspect ratio or extending spatial canvas beyond original frame.",
  },
  {
    name: "ai-music",
    description: "Smart router across music-model catalog — ElevenLabs AI Music (premium 44.1 kHz, $0.0083/s) and ACE Step (open-weights, $0.0002-0.0003/s, ~27× cheaper). Inpaint and outpaint audio.",
    triggers: ["generate music", "make a song", "AI music", "background music", "soundtrack", "jingle", "extend music", "inpaint music"],
    category: "media-gen",
    combos: ["runcomfy-cli", "elevenlabs-music-generation", "ace-step"],
    whenToUse: "For any music generation — picks between premium ElevenLabs and cheap ACE Step.",
  },
  {
    name: "elevenlabs-music-generation",
    description: "Generate full songs with ElevenLabs Music — studio-quality 44.1 kHz stereo, 5s-5min, section-level control (Intro/Verse/Chorus/Bridge), multilingual vocals.",
    triggers: ["ElevenLabs Music", "premium music", "vocal track", "studio quality music"],
    category: "media-gen",
    combos: ["ai-music", "runcomfy-cli", "ace-step"],
    whenToUse: "When you need premium 44.1 kHz stereo vocal tracks with section control.",
  },
  {
    name: "ace-step",
    description: "Generate, inpaint, and outpaint music with ACE Step (StepFun-AI open-weights) — tag-driven composition, multilingual lyrics, 5s-4min, $0.0002-0.0003/s.",
    triggers: ["ace step", "ACE music", "open music model", "cheap AI music", "inpaint audio", "audio outpaint"],
    category: "media-gen",
    combos: ["ai-music", "runcomfy-cli", "elevenlabs-music-generation"],
    whenToUse: "For cheap, tag-driven music generation — ~27× cheaper than ElevenLabs.",
  },
  {
    name: "happyhorse-1-0",
    description: "Generate text-to-video with HappyHorse 1.0 — #1 on Arena, native 1080p with in-pass synchronized audio, multi-shot character consistency.",
    triggers: ["happyhorse", "happy horse", "happyhorse 1.0", "arena #1 video"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "wan-2-7"],
    whenToUse: "When you want HappyHorse 1.0 specifically — Arena #1 with in-pass audio.",
  },
  {
    name: "wan-2-7",
    description: "Generate text-to-video with Wan 2.7 (Wan-AI flagship motion model) — multi-reference conditioning, audio-driven lip-sync, smooth transitions.",
    triggers: ["wan", "wan 2.7", "wan video", "wan-ai"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "happyhorse-1-0"],
    whenToUse: "When you want Wan 2.7 specifically — open weights, lip-sync, multi-reference.",
  },
  {
    name: "seedance-v2",
    description: "Generate cinematic short-form video with ByteDance Seedance 2.0 Pro — multi-modal references (up to 9 images, 3 videos, 3 audio), natural lip-sync.",
    triggers: ["seedance", "seedance 2", "seedance v2", "seedance pro", "bytedance video"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "image-to-video"],
    whenToUse: "For cinematic short-form with multiple reference inputs — images, videos, audio.",
  },
  {
    name: "kling-3-0",
    description: "Kling 3.0 video generation — Kuaishou's third-gen multi-shot model with native synchronized audio and consistent character identity. Standard, Pro, and 4K tiers.",
    triggers: ["kling", "kling 3.0", "kling v3", "kling pro", "kling 4k"],
    category: "media-gen",
    combos: ["ai-video-generation", "runcomfy-cli", "video-edit"],
    whenToUse: "When you want Kling 3.0 specifically — multi-shot with native audio, 3 quality tiers.",
  },
  {
    name: "ai-avatar-video",
    description: "Create AI avatar, talking-head, and lip-sync videos — OmniHuman, Wan 2-7 lip-sync, HappyHorse 1.0 with audio, Seedance v2 Pro. Routes based on intent.",
    triggers: ["talking head", "lip sync", "avatar video", "make X speak", "audio to video", "virtual presenter", "HeyGen alternative", "Synthesia alternative"],
    category: "media-gen",
    combos: ["lipsync", "ai-video-generation", "runcomfy-cli"],
    whenToUse: "For creating videos where a face speaks — virtual presenters, dubbed content, avatars.",
  },
  {
    name: "lipsync",
    description: "Lip-sync a face to audio — OmniHuman (full-body avatar), Sync Labs sync v2/Pro (mouth sync on video), Kling lipsync, Creatify lipsync.",
    triggers: ["lip sync", "lipsync", "make this video speak", "match audio to mouth", "dub video", "Sync Labs", "voiceover sync"],
    category: "media-gen",
    combos: ["ai-avatar-video", "runcomfy-cli", "face-swap"],
    whenToUse: "For driving mouth movements from audio on portrait or video.",
  },
  {
    name: "face-swap",
    description: "Swap a face/character into video or images — Wan 2-2 Animate, GPT Image 2 Edit, Nano Banana Edit, Flux Kontext, Kling 2-6 Motion Control Pro.",
    triggers: ["face swap", "swap face", "deepfake", "character swap", "head swap", "put X's face on Y", "ReActor alternative"],
    category: "media-gen",
    combos: ["lipsync", "ai-avatar-video", "runcomfy-cli"],
    whenToUse: "For replacing one identity with another in video or still images.",
  },
  {
    name: "controlnet-pose",
    description: "Pose-conditioned generation — Kling 2-6 Motion Control, Wan 2-2 Animate (audio-driven + pose), Z-Image Turbo ControlNet LoRA (OpenPose/DWPose/canny/depth).",
    triggers: ["controlnet", "pose control", "openpose", "DWPose", "transfer pose", "motion control", "canny edge"],
    category: "media-gen",
    combos: ["ai-image-generation", "ai-video-generation", "runcomfy-cli"],
    whenToUse: "When conditioning generation on pose, skeleton, motion, depth, or canny reference.",
  },
  {
    name: "codex-pet",
    description: "Build a Codex-compatible Codex Pet spritesheet.webp + pet.json from a single reference image. 1536x1872 atlas, 9 animation states.",
    triggers: ["codex pet", "create codex pet", "make codex pet", "hatch codex pet", "spritesheet.webp", "desktop pet"],
    category: "media-gen",
    combos: ["runcomfy-cli", "gpt-image-2"],
    whenToUse: "For creating custom desktop pets for OpenAI Codex from a reference image.",
  },
  {
    name: "runcomfy-cli",
    description: "Run any model on RunComfy from CLI — one binary, one auth, hundreds of endpoints. Image/video gen, edit, lip-sync, face swap, inpainting, upscale, LoRA training.",
    triggers: ["runcomfy cli", "install runcomfy", "runcomfy login", "runcomfy run", "runcomfy whoami"],
    category: "tooling",
    combos: ["ai-image-generation", "ai-video-generation", "ai-music", "image-edit", "video-edit"],
    whenToUse: "Foundation for all RunComfy operations — install, auth, and invoke any model endpoint.",
  },
  {
    name: "deploy-to-vercel",
    description: "Deploy applications and websites to Vercel — push live, create preview deployments, manage projects.",
    triggers: ["deploy my app", "deploy to vercel", "push live", "preview deployment"],
    category: "tooling",
    combos: ["vercel-cli-with-tokens", "vercel-optimize"],
    whenToUse: "For deploying apps to Vercel and creating preview/production deployments.",
  },
  {
    name: "vercel-cli-with-tokens",
    description: "Deploy and manage projects on Vercel using token-based authentication — no interactive login needed.",
    triggers: ["vercel token", "vercel env", "deploy with token", "vercel CLI"],
    category: "tooling",
    combos: ["deploy-to-vercel", "vercel-optimize"],
    whenToUse: "For automated Vercel deployments using access tokens instead of interactive login.",
  },
  {
    name: "mcp-builder",
    description: "Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools.",
    triggers: ["MCP server", "Model Context Protocol", "build MCP", "FastMCP"],
    category: "tooling",
    combos: ["brainstorming", "writing-plans", "tdd"],
    whenToUse: "When building MCP servers in Python (FastMCP) or Node/TypeScript (MCP SDK).",
  },
  {
    name: "customize-opencode",
    description: "Edit opencode's configuration — opencode.json, .opencode/, agents, subagents, skills, plugins, MCP servers, permission rules.",
    triggers: ["opencode config", ".opencode", "opencode.json", "configure opencode"],
    category: "tooling",
    combos: ["skill-creator", "mcp-builder"],
    whenToUse: "ONLY when editing opencode's own configuration files.",
  },
  {
    name: "claude-api",
    description: "Reference for Claude API / Anthropic SDK — model IDs, pricing, params, streaming, tool use, MCP, agents, caching, token counting, model migration.",
    triggers: ["Claude API", "Anthropic SDK", "model pricing", "token count", "streaming", "tool use"],
    category: "tooling",
    combos: ["mcp-builder", "brainstorming"],
    whenToUse: "When working with Claude/Anthropic APIs — pricing, models, caching, tool definitions.",
  },
  {
    name: "web-design-guidelines",
    description: "Review UI code for Web Interface Guidelines compliance — accessibility, UX, design best practices.",
    triggers: ["review my UI", "check accessibility", "audit design", "review UX", "best practices"],
    category: "code",
    combos: ["frontend-design", "redesign-existing-projects", "webapp-testing"],
    whenToUse: "For auditing UI code against web interface guidelines and accessibility standards.",
  },
];

export const categories = [
  { id: "process", label: "Process & Workflow", color: "#b8860b" },
  { id: "design", label: "Design & Visual", color: "#c73e3a" },
  { id: "media-gen", label: "Media Generation", color: "#6a3fb8" },
  { id: "code", label: "Code & Engineering", color: "#2b7a4b" },
  { id: "tooling", label: "Tooling & Infrastructure", color: "#1a6b8a" },
  { id: "docs", label: "Documents & Writing", color: "#8b7b6b" },
] as const;

export const comboSuggestions = [
  {
    scenario: "Building a new feature from scratch",
    skills: ["brainstorming", "writing-plans", "tdd", "subagent-driven-development", "finishing-a-development-branch"],
    description: "Full feature lifecycle: design → plan → implement with TDD → review → merge.",
  },
  {
    scenario: "Fixing a hard bug",
    skills: ["diagnose", "systematic-debugging", "tdd", "verification-before-completion"],
    description: "Scientific debugging loop: reproduce, minimize, fix, verify with tests.",
  },
  {
    scenario: "Creating a landing page",
    skills: ["brainstorming", "design-taste-frontend", "frontend-design", "imagegen-frontend-web", "image-to-code"],
    description: "Design-first approach: brainstorm → generate design refs → implement faithfully.",
  },
  {
    scenario: "Generating AI media (images/video/music)",
    skills: ["ai-image-generation", "ai-video-generation", "ai-music", "runcomfy-cli"],
    description: "Route through smart catalog routers that pick the best model for each task.",
  },
  {
    scenario: "Creating a presentation or document",
    skills: ["brainstorming", "pptx", "theme-factory", "writing-guidelines", "pdf"],
    description: "Plan content → create slides with theme → export to PDF.",
  },
  {
    scenario: "Deploying to production",
    skills: ["deploy-to-vercel", "vercel-cli-with-tokens", "vercel-optimize", "verification-before-completion"],
    description: "Verify everything passes → deploy → optimize for cost and performance.",
  },
  {
    scenario: "Setting up a new project",
    skills: ["setup-matt-pocock-skills", "brainstorming", "using-git-worktrees", "shadcn"],
    description: "Configure agent context → design architecture → isolate workspace → set up UI.",
  },
  {
    scenario: "Writing documentation",
    skills: ["doc-coauthoring", "writing-guidelines", "internal-comms", "docx"],
    description: "Structured co-authoring → review for style → export to polished format.",
  },
  {
    scenario: "Code review cycle",
    skills: ["requesting-code-review", "receiving-code-review", "verification-before-completion"],
    description: "Request review → process feedback rigorously → verify fixes before claiming done.",
  },
  {
    scenario: "Architecture improvement",
    skills: ["improve-codebase-architecture", "zoom-out", "brainstorming", "grill-with-docs"],
    description: "Zoom out to see big picture → find deepening opportunities → stress-test against docs.",
  },
  {
    scenario: "Managing issues and triage",
    skills: ["to-issues", "to-prd", "triage", "setup-matt-pocock-skills"],
    description: "Convert plans to issues → triage incoming items → manage workflow states.",
  },
  {
    scenario: "Creating an AI avatar or talking head video",
    skills: ["ai-avatar-video", "lipsync", "face-swap", "runcomfy-cli"],
    description: "Generate avatar → sync lips to audio → optionally swap face identity.",
  },
];
